export const queryKeys = {
  auth: ['auth'] as const,
  profile: ['profile'] as const,
  securitySessions: ['security-sessions'] as const,
  people: (query: string) => ['people', query] as const,
  friendRequests: ['friend-requests'] as const,
  conversations: (filters?: string) => ['conversations', filters ?? 'all'] as const,
  conversation: (conversationId: string) => ['conversation', conversationId] as const,
  messages: (conversationId: string) => ['messages', conversationId] as const,
  group: (groupId: string) => ['group', groupId] as const,
  notifications: (unreadOnly: boolean) => ['notifications', unreadOnly] as const,
  privacy: ['privacy'] as const,
  reports: ['my-reports'] as const,
  savedMessages: ['saved-messages'] as const,
  messageSearch: (query: string, conversationId?: string) =>
    ['message-search', query, conversationId ?? 'all'] as const,
  adminDashboard: ['admin-dashboard'] as const,
  adminUsers: (filters: unknown) => ['admin-users', filters] as const,
  adminUser: (userId: string) => ['admin-user', userId] as const,
  adminReports: (filters: unknown) => ['admin-reports', filters] as const,
  adminReport: (reportId: string) => ['admin-report', reportId] as const,
  adminGroups: (filters: unknown) => ['admin-groups', filters] as const,
  adminAudit: (filters: unknown) => ['admin-audit', filters] as const,
} as const
