export const routes = {
  landing: '/',
  login: '/login',
  register: '/register',
  conversations: '/conversations',
  conversation: (conversationId: string) => `/conversations/${conversationId}`,
  people: '/people',
  friendRequests: '/people/requests',
  createGroup: '/groups/new',
  groupDetails: (groupId: string) => `/groups/${groupId}`,
  groupAdministration: (groupId: string) => `/groups/${groupId}/manage`,
  search: '/search',
  notifications: '/notifications',
  reports: '/reports',
  profile: '/profile',
  privacy: '/privacy',
  security: '/security',
  savedMessages: '/saved',
  admin: '/admin',
  adminUsers: '/admin/users',
  adminReports: '/admin/reports',
  adminGroups: '/admin/groups',
  adminAudit: '/admin/audit',
} as const
